### ISSUE TITLE
Remove dependency on apache commons

### ISSUE THREAD

**Issue by chinmaymk** [yevgenlisovenko/LogCollection#2]
Hey Yevgen,

This is Chinmay from cribl. I see you're using apache commons for some operations in the codebase. As the exercise recommends to keep dependencies to a minimum, could you try implementing those bits without using apache commons?

**Comment by yevgenlisovenko** [comment]
Hi Chinmay,
I utilized ReversedLinesFileReader from commons.io to read log file line by line from the end.
I know that internally ReversedLinesFileReader uses RandomAccessFile (java.io) to read the file from the end.
I'll work to get rid of commons.io dependency.

**Comment by chinmaymk** [comment]
thank you!

**Comment by yevgenlisovenko** [comment]
I have removed commons.io dependency by implementing custom ReversedFileReader, which uses own buffer to read portions of bytes from the end of file until end of previous line reached (or beginning of file). This way it will work faster than reading byte by byte from the disk.
